language: node_js
node_js:
  - "9.2.0"
cache:
  directories:
  - node_modules
script:
deploy:
  provider: heroku
  api_key: 
    secure: $heroku_token
  app: mysterious-mountain-84375
  skip_cleanup: true
  on:
    repo: gavin771/emailer-server
    branch: master